### ISSUE TITLE
the recommender page still says "User" instead of the name of the person being recommended

### ISSUE THREAD

**Issue by gvelez17** [Cooperation-org/linked-claims-author#182] opened 2024-11-05 04:58 UTC

**Comment by dev-mhany** [comment] 2024-11-05 05:32
that's becuase the recommender didn't sign in thus the data couldn't be fetched
![image](https://github.com/user-attachments/assets/664e22b5-7029-4cf6-83eb-f5b3c7af218a)
when the recommender sign in (access token available)we could view the name and email
![image](https://github.com/user-attachments/assets/6e9ed293-2d35-4eca-8421-1942d099e4e9)
"if (credentialSubject?.name) {
setFullName(credentialSubject.name)
} else {
setFullName('User')
}"
we could change the language and we are up to any suggestions.

**Comment by AmrNabel** [comment] 2024-11-05 09:20
We can make if the user is not signed, not showing anything except sign to make your recommendation

**Comment by dev-mhany** [comment] 2024-11-05 12:03
@AmrNabel, it appears that the scoop issue was the cause.

**Comment by 0marSalah** [comment] 2024-11-27 11:07
this is oudated issue, i am gonna close it

**Closed** 2024-11-27 11:08 UTC
